In [90]:
def syracuse(n):
    """ Retourne la liste des valeurs de la suite en partant de n jusqu'à 1 """
    valeurs_suite_syracuse = []
    while n != 1:
        valeurs_suite_syracuse += [int(n)]
        if n % 2 == 0:
            n /= 2
        else : 
            n = n*3 + 1 
    valeurs_suite_syracuse.append(1)   
    return (valeurs_suite_syracuse)

In [91]:
print(syracuse(3))

[3, 10, 5, 16, 8, 4, 2, 1]


In [92]:
def testeConjecture(n_max):
    """ Teste la conjecture de Collatz pour toutes les valeurs de 2 à n_max """
    test = True
    iteration = 1 
    while iteration <= n_max and test:
          test = syracuse(iteration)[len(syracuse(iteration))-1] == 1
          iteration += 1
    return test 
            

In [93]:
print(testeConjecture(10000))

True


In [94]:
def tempsVol(n):
    """ Retourne le temps de vol de n """
    return len(syracuse(n))-1 

In [95]:
print("Le temps de vol de", 3, "est", tempsVol(3))

Le temps de vol de 3 est 7


In [96]:
def tempsVolListe(n_max):
    """ Retourne la liste de tous les temps de vol de 1 à n_max """
    return [len(syracuse(n))-1 for n in range(1,n_max + 1)]

In [97]:
print(tempsVolListe(100))
print(len(tempsVolListe(100)))

[0, 1, 7, 2, 5, 8, 16, 3, 19, 6, 14, 9, 9, 17, 17, 4, 12, 20, 20, 7, 7, 15, 15, 10, 23, 10, 111, 18, 18, 18, 106, 5, 26, 13, 13, 21, 21, 21, 34, 8, 109, 8, 29, 16, 16, 16, 104, 11, 24, 24, 24, 11, 11, 112, 112, 19, 32, 19, 32, 19, 19, 107, 107, 6, 27, 27, 27, 14, 14, 14, 102, 22, 115, 22, 14, 22, 22, 35, 35, 9, 22, 110, 110, 9, 9, 30, 30, 17, 30, 17, 92, 17, 17, 105, 105, 12, 118, 25, 25, 25]
100


In [98]:
def max_tempsVolListe(n_max):
    return max(tempsVolListe(n_max)), tempsVolListe(n_max).index(max(tempsVolListe(n_max))) + 1

In [99]:
print(max_tempsVolListe(10000))

(261, 6171)


In [100]:
def altitude_maximale(n_max):
    """renvoie l'entier compris entre 1 et n_max ayant la plus grande altitude maximale"""
    altitude_maximale_n = [max(syracuse(i)) for i in range(1, n_max +1)]
    return max(altitude_maximale_n), altitude_maximale_n.index(max(altitude_maximale_n)) + 1

In [101]:
print(altitude_maximale(10000))

(27114424, 9663)


In [35]:
carre_mag = [[4, 14, 15, 1], [9, 7, 6, 12], [5, 11, 10, 8], [16, 2, 3, 13]]
print(carre_mag)

[[4, 14, 15, 1], [9, 7, 6, 12], [5, 11, 10, 8], [16, 2, 3, 13]]


In [36]:
carre_pas_mag = []
for i in range(0, len(carre_mag)):
    carre_pas_mag.append(carre_mag[i].copy())
for i in range(0,len(carre_pas_mag)): 
    if 3 in carre_pas_mag[i] : 
        carre_pas_mag[i][carre_pas_mag[i].index(3)] = 7 
print(carre_pas_mag, carre_mag)

[[4, 14, 15, 1], [9, 7, 6, 12], [5, 11, 10, 8], [16, 2, 7, 13]] [[4, 14, 15, 1], [9, 7, 6, 12], [5, 11, 10, 8], [16, 2, 3, 13]]


In [37]:
import numpy as np
def afficheCarre(carre):
    """la fonction permet d'afficher les listes deux dimensions sous forme de carrés"""
    return np.array(carre)

In [38]:
print(afficheCarre(carre_mag))
print(afficheCarre(carre_pas_mag))

[[ 4 14 15  1]
 [ 9  7  6 12]
 [ 5 11 10  8]
 [16  2  3 13]]
[[ 4 14 15  1]
 [ 9  7  6 12]
 [ 5 11 10  8]
 [16  2  7 13]]


In [65]:
def testLignesEgales(carre):
    """ Renvoie la somme des éléments d'une ligne de la liste 2D carre si toutes les lignes ont la même somme, et -1 sinon """
    sum_ligne = sum(carre[0])
    for i in range(1, len(carre)):
        if sum(carre[i]) != sum_ligne:
            sum_ligne = -1
            break
    return sum_ligne

In [70]:
print(testLignesEgales(carre_mag))
print(testLignesEgales(carre_pas_mag))

34
-1


In [ ]:
def testColonnesEgales(carre):
    """ Renvoie la somme des éléments d'une colonne de la liste 2D carre si toutes les colonnes ont la même somme, et -1 sinon """
    carre_par_colonne = []
    for i in carre:
        carre_par_colonne.append()
